/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IUnipilotInterface extends ethers.utils.Interface {
  functions: {
    "createPoolAndDeposit((address,address,address,address,uint256,uint256),bytes[2])": FunctionFragment;
    "deposit((address,address,address,address,uint256,uint256),bytes)": FunctionFragment;
    "governance()": FunctionFragment;
    "mintPilot(address,uint256)": FunctionFragment;
    "mintUnipilotNFT(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPoolAndDeposit",
    values: [
      {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      [BytesLike, BytesLike]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [
      {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintPilot",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintUnipilotNFT",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPoolAndDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPilot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintUnipilotNFT",
    data: BytesLike
  ): Result;

  events: {};
}

export class IUnipilot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IUnipilotInterface;

  functions: {
    createPoolAndDeposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: [BytesLike, BytesLike],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    mintPilot(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintUnipilotNFT(
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createPoolAndDeposit(
    params: {
      sender: string;
      exchangeAddress: string;
      token0: string;
      token1: string;
      amount0Desired: BigNumberish;
      amount1Desired: BigNumberish;
    },
    data: [BytesLike, BytesLike],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposit(
    params: {
      sender: string;
      exchangeAddress: string;
      token0: string;
      token1: string;
      amount0Desired: BigNumberish;
      amount1Desired: BigNumberish;
    },
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  governance(overrides?: CallOverrides): Promise<string>;

  mintPilot(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintUnipilotNFT(
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPoolAndDeposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: [BytesLike, BytesLike],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        amount0Base: BigNumber;
        amount1Base: BigNumber;
        amount0Range: BigNumber;
        amount1Range: BigNumber;
        mintedTokenId: BigNumber;
      }
    >;

    deposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        amount0Base: BigNumber;
        amount1Base: BigNumber;
        amount0Range: BigNumber;
        amount1Range: BigNumber;
        mintedTokenId: BigNumber;
      }
    >;

    governance(overrides?: CallOverrides): Promise<string>;

    mintPilot(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    mintUnipilotNFT(
      sender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    createPoolAndDeposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: [BytesLike, BytesLike],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    mintPilot(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintUnipilotNFT(
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPoolAndDeposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: [BytesLike, BytesLike],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      params: {
        sender: string;
        exchangeAddress: string;
        token0: string;
        token1: string;
        amount0Desired: BigNumberish;
        amount1Desired: BigNumberish;
      },
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintPilot(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintUnipilotNFT(
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
