/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUnipilotFarmV1,
  IUnipilotFarmV1Interface,
} from "../IUnipilotFarmV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "poolInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "startBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "globalReward",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastRewardBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalLockedLiquidity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rewardMultiplier",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isRewardActive",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isAltActive",
            type: "bool",
          },
        ],
        internalType: "struct IUnipilotFarmV1.PoolInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUnipilotFarmV1__factory {
  static readonly abi = _abi;
  static createInterface(): IUnipilotFarmV1Interface {
    return new utils.Interface(_abi) as IUnipilotFarmV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUnipilotFarmV1 {
    return new Contract(address, _abi, signerOrProvider) as IUnipilotFarmV1;
  }
}
