/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUniStrategy, IUniStrategyInterface } from "../IUniStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "getTicks",
    outputs: [
      {
        internalType: "int24",
        name: "baseLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "baseUpper",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "bidLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "bidUpper",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "askLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "askUpper",
        type: "int24",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pricethreshold",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IUniStrategyInterface {
    return new utils.Interface(_abi) as IUniStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniStrategy {
    return new Contract(address, _abi, signerOrProvider) as IUniStrategy;
  }
}
