/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUnipilotStake,
  IUnipilotStakeInterface,
} from "../IUnipilotStake";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "poolAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getBoostMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "poolAddress",
        type: "address",
      },
    ],
    name: "userMultiplier",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUnipilotStake__factory {
  static readonly abi = _abi;
  static createInterface(): IUnipilotStakeInterface {
    return new utils.Interface(_abi) as IUnipilotStakeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUnipilotStake {
    return new Contract(address, _abi, signerOrProvider) as IUnipilotStake;
  }
}
